## Numpy Review ##

### Numpy Arrays ###

In [3]:
import numpy as np

In [7]:
my_list=[1,2,3,4]

In [10]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3, 4])

In [13]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [17]:
matrix=np.array(my_mat)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matrix.shape

(3, 3)

***Create your own array***

In [21]:
np.arange(0,10)
np.arange(0,10,2) #by steps

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

LinSpace  
Return evenly spaced *points* over some interval. Not to be confused with range. Takes 3 items, including how many points you want

In [29]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

Identity Matrix

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random Numbers

In [33]:
np.random.rand(5) #returns 5 random but uniformly distribued numbers

array([0.20203514, 0.49592642, 0.76003664, 0.71335451, 0.23279564])

In [34]:
np.random.rand(2,3)

array([[0.0429623 , 0.78260343, 0.77066761],
       [0.76661382, 0.37014082, 0.64373492]])

In [35]:
np.random.randn(5)  #standard normal distribution centered around 0

array([ 2.58540695,  0.06861002, -0.18675756, -0.25431385,  2.3930023 ])

In [37]:
np.random.randint(1,100,10)  #returns random integers from a low to a high number. high is not included

array([88, 38, 79, 21, 59, 83, 85, 83, 43, 89])

***Useful Attribtes and Methods***

In [42]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranr=np.random.randint(0,50,10)
ranr

array([24, 12, 30,  6, 26, 48, 13,  5,  7, 14])

In [47]:
#reshape
arr.shape #(25,)
arr.reshape(5,5) #need to fill it up otherwise, you will get an error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
#max/min values
ranr.max(), ranr.min()

(48, 5)

In [53]:
#location of max, min
ranr.argmax(), ranr.argmin()

(5, 7)

In [54]:
arr.dtype

dtype('int64')

### Numpy Indexing and Selection ###

In [57]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[:5], arr[5:]

(array([0, 1, 2, 3, 4]), array([ 5,  6,  7,  8,  9, 10]))

***Broadcasting and Slicing***

In [63]:
arr[0:5]=100

In [64]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
arr = np.arange(0,11) #reset

In [66]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [67]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

BUT:

In [69]:
arr  #so slice_of_array is just a view of the original array and hence the original array is affected. 
#numpy does this due to memory mgmt

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
#so use copy
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [75]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

***2D Arrays***

In [89]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
arr_2d.shape

(3, 3)

*Double Bracket Format*

In [82]:
arr_2d[0][0]  #[row][column]

5

In [83]:
arr_2d[0]

array([ 5, 10,  5])

In [86]:
#for element for 25, 45
arr_2d[1][1], arr_2d[2][2]

(25, 45)

*Comma Single Bracket Notation*

In [87]:
arr_2d[1,2]  #[row,column]

30

In [88]:
#so fo 40
arr_2d[2,1]

40

Slicing 2D arrays

In [92]:
#grab [10,15 and 25,30]
arr_2d[:2,1:] #[row, column]

array([[10, 15],
       [25, 30]])

In [93]:
#grab [25,30] and [40,45]
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [98]:
#grab [35,40,45]
arr_2d[2:,] #or arr_2d[2:,:] or arr_2d[2:]

array([[35, 40, 45]])

***Conditional Selection***

In [99]:
#create a new array
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
bool_arr=arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [102]:
arr[bool_arr] #returns only True values from bool_arr

array([ 6,  7,  8,  9, 10])

In [103]:
#in one step
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [104]:
arr[arr<3]

array([1, 2])

***Some More Examples***

In [106]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [108]:
#slice off 7,17,27
arr_2d[:3,7:8]

array([[ 7],
       [17],
       [27]])

### Numpy Operations ###  

* Array with Array
* Array with Scalars
* Universal Array Functions

In [109]:
arr = np.arange(0,11)

In [113]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [114]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [118]:
#scalar operations
arr+100
arr*100
arr/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

Notice what happens, when dividing by zero or if elements have zero. You will not get an error rather a warning.

In [124]:

arr/0

/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [125]:
arr/arr

/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [126]:
1/arr

/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [127]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

***Universal Array Functions***  
See more at: 
[https://docs.scipy.org/doc/numpy/reference/ufuncs.html](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [129]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [131]:
np.log(arr)

/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [132]:
np.max(arr), np.min(arr)

(10, 0)

In [133]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])